didoesdigital/steno-dictionaries

dictionaries/nouns.json, dictionaries/top-10000-project-gutenberg-words.json
=> Change stroke for 'spake' to be fingerspelling

dictionaries/condensed-strokes.json
=> Add stroke PWREUPBGS for 'brings' to condensed-strokes dictionary

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Update stroke entries for "bless"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Update Typey-Type stroke for 'blast' from PWRAFT to PWHRAFT. 

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Fix stroke entry for 'dealing'.

dictionaries/top-10000-project-gutenberg-words.json
=> Change Gutenberg dictionary stroke for "major". 

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark STEUPGS for "estimation" as a mis-stroke. 

dictionaries/dict-en-AU-with-extra-stroke.json, dictionaries/nouns.json
Forms part of the solution to #96.
=> Add entry for AU-spelling of "civilisation".

dictionaries/top-10000-project-gutenberg-words.json
=> Change stroke for 'violation' from SROEULGS to SRAOEULGS

dictionaries/bad-habits.json, dictionaries/briefs.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Remove non-existent single-stroke entry for "expansion"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Change stroke for 'completely' from KPHRELT to KPHRAOELT. 

dictionaries/dict.json
=> Add PWES/TOE stroke for "bestow" to dict.json. 

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark "impressions" stroke that does not use SG for the "shun" sound as a mis-stroke

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Add Plover stroke R*EFRS for "reverse" to dictionaries. 

dictionaries/top-10000-project-gutenberg-words.json
=> Add `F` stroke to stroke for "events".

dictionaries/top-10000-project-gutenberg-words.json
=> Change Gutenberg dictionary entry for "extensive" to non-brief stroke

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Add new `"PRABGT": "practical"` stroke to `dict.json`

dictionaries/top-10000-project-gutenberg-words.json
=> Change stroke for "inaccessible" to be the currently "official" one from Plover

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
=> Update capitalisation in stroke for "Hastings".

dictionaries/condensed-strokes.json, dictionaries/nouns.json, dictionaries/top-10000-project-gutenberg-words.json
=> Add new condensed strokes for "mightily".

dictionaries/top-10000-project-gutenberg-words.json
=> Change outline for "ab" to fingerspelling.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes some dictionary fixes (details in each commit message) that came up for me working through Typey Type's [Suffix and prefix briefs lesson](https://didoesdigital.com/typey-type/lessons/drills/suffix-and-prefix-briefs/).
=> "Suffix and prefix briefs" lesson fixes

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json
This PR proposes a set of fixes and additions based on what I found while doing Typey Type's [Apostrophes lesson](https://didoesdigital.com/typey-type/lessons/drills/apostrophes/). Details are in each of the commit messages.
=> Apostrophes fixes

dictionaries/condensed-strokes.json
This PR proposes to add some condensed strokes for words I came across in the Puss in Boots lesson on Typey Type.
=> Add condensed strokes

README.md
fix the stroke to be `HRO*ERZ`
=> README: fix stroke for `{MODE:LOWER}`

README.md
=> README: fix description for `{PLOVER:QUIT}`
