dictionaries/top-10000-project-gutenberg-words.json
A change in capitalisation for "John" in the Project Gutenberg dictionary entry for `SKWROPB` would bring it in line with all the other dictionaries. For example:
https://github.com/didoesdigital/steno-dictionaries/blob/5eaf4f5fb55e422c00aad2df8f34d5a9552dca0a/dictionaries/top-10000-english-words.json#L373
https://github.com/didoesdigital/steno-dictionaries/blob/5eaf4f5fb55e422c00aad2df8f34d5a9552dca0a/dictionaries/top-1000-words.json#L379
=> Fix capitalisation of 'John' in Project Gutenberg dictionary

dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
`S*/TPH*` outputs "sn" in lowercase, so fix the capitalisation of the "Sn" entry to `S*K/TPH*`.
=> Fix capitalisation in keystroke for 'Sn'

dictionaries/top-1000-words.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
Change keystroke for 'er' to its finger-spelling, and remove trailing `SP-S` from keystroke for 'ye'.
Fixes #7
=> Fix entries for 'er' and 'ye'

dictionaries/dict.json, dictionaries/top-1000-words.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
In the Plover dictionary for release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), `PHA*EUT` outputs "m8", so this pull requests proposes to:
- Remove `PHA*EUT` from `dict.json` as a stroke for "faith", since it would seem it's no longer correct
- Change the keystroke in all dictionary references for "faith" to `TPA*EUT`
=> Change "faith" stroke from PHA*EUT to TPA*EUT

dictionaries/top-1000-words.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
Although both `KHARLS` and `KHARLZ` are valid strokes for "Charles" in Plover, I propose to substitute its entry from `KHARLZ` to `KHARLS` in Typey-Type because:
- It's easier to stroke (your pinky doesn't need to reach for `Z`)
- Phonetically, the name "Charles" doesn't necessarily end with a strong "Z" sound
=> Stroke KHARLS rather than KHARLZ for "Charles" in Typey-Type

dictionaries/condensed-strokes.json, dictionaries/nouns.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
The stroke `ETS/TP-PL` outputs "et cetera." in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), so this proposal changes the entry to the new `*ETS` stroke for the abbreviated "etc."
=> Fix stroke for "etc."

dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
Follow up to #14. Somehow changing the remote branch name automatically closed the PR, and I couldn't seem to re-open it. Sorry about that!
=> Change dictionary entries for UK spelling of 'honour' to finger-spelling.

dictionaries/condensed-strokes.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), `5R` outputs uppercase "V", so this PR proposes to change the stroke for "v." from uppercase `5R/TP-PL` to the finger-spelled lowercase `SR*/TP-PL`.
=> Change the stroke for 'v.' to output lowercase instead of uppercase

dictionaries/condensed-strokes.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), `O*/AE` outputs as uppercase "O'", so change stroke for lowercase "o'" to the correct `OE/AE`.
=> O*/AE outputs as "O'", so change stroke for "o'" to O*/TK-LS/AE

dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
Since there is no `EFD` stroke in the current `dict.json`, or the Plover dictionaries, for "evidence", I'm assuming that its use in the `top-10000-*.json` dictionaries is a typo. So, this PR fixes it to its correct `*EFD` stroke.
=> Fix typo in stroke for "evidence"

dictionaries/condensed-strokes.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
Add `EPB/TKPWAEUPBLGD` condensed stroke for "engaged" in `condensed-strokes.json`, and have the Typey Type dictionaries use it. The only real reason for this proposal is that it's one stroke less than the current `EPB/TKPWAEUBLG/-D` stroke, and doesn't, in my opinion, make the stroke more difficult or convoluted to execute.
=> Add EPB/TKPWAEUPBLGD condensed stroke for "engaged"

dictionaries/condensed-strokes.json, dictionaries/nouns.json
"SELTD": "settled", "SELTG": "settling", and "SELTS": "settles", can all
be written without explicit entries using Plover’s orthography rules. We
add explicit entries to condensed strokes to improve Typey Type
suggestions and improve brief look ups.
Fixes #28
=> Add "SELT": "settle" and suffixes

dictionaries/dict.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the stroke for "seas" from `SAEZ`, to its easier-to-stroke counterpart `SAES` for that reason only, not because of any correctness issues with `SAEZ`.
`dict.json` already has an entry for `SAES` as "satisfies", but as of Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), it would seem that this is now incorrect, and hence there is a separate commit to change it to the now-correct "seas".
If it's not worth changing the `"SAEZ": "seas"` entry in Typey Type dictionaries, I'm happy to take that commit out of this PR and just leave the fix for `"SAES": "satisfies"`.
=> Change "seas" from SAEZ to SAES

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to remove the `WAED` stroke for "wade", as it would seem to have been removed from Plover as of release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), and updates the Typey-Type dictionary to use `WAEUD` for "wade" instead.
=> Remove WAED stroke for "wade"

dictionaries/dict.json, dictionaries/top-10000-english-words.json
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) would seem to have changed the `KOEF` stroke meaning from "cove" to "coffee", so this PR:
- Fixes the `KOEF` entry
- Reflects this change in the Typey-Type dictionary so that "cove" now uses the `KO*EF` stroke
=> Fix entry for KOEF stroke from "cove" to "coffee"

dictionaries/dict.json, dictionaries/top-10000-english-words.json
As of Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the stroke `PHO` resolves to "no", which means that there is now not a specific stroke available for the "mo" entry. Therefore, the PR proposes a change to its fingerspelling.
=> Change stroke for "mo" entry to its fingerspelling

dictionaries/dict.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
As of Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the stroke `TPAULS` resolves to "falls", rather than "false". This means that "falls" can now be stroked a bit easier using `TPAULS`, rather than stretching for the Z in `TPAULZ`. Therefore, this PR:
- Changes the entry for the `TPAULS` stroke from "false" to "falls"
- Changes Typey-Type dictionaries to reference the new subjectively-easier-to-stroke `TPAULS` for "falls"
=> Change stroke for falls from TPAULZ to TPAULS

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-english-words.json
As of Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the stroke `TKPWEUS` no longer resolves to "guys", but to "GIS", so this PR:
- Changes the entry for the `TKPWEUS` stroke from "guys" to "GIS"
- Changes the Typey-Type dictionaries to use the `TKPWAOEUS` stroke for "guys" (there are other strokes that could be used here, so this is a subjective proposal on my part; it just felt like the easiest and most logical stroke to me)
=> Change stroke for "guys" from TKPWEUS to TKPWAOEUS

dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
All the strokes for "Mars" are currently in the dictionaries, but this PR just proposes that the stroke Typey-Type uses is changed from `PHARZ` to `PHARS` to forgo reaching for the `Z` when an `S` will do.
=> Use easier-to-stroke PHARS for 'Mars', rather than PHARZ

dictionaries/dict.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
This PR does the following related to human names:
- fixes the discrepancy for `PWRAD`, `PWO`, `HREUZ`, and `PHEL` entries between `dict.json` (where they are correct) and Typey-Type dictionaries (where they are incorrect).
- fixes the stroke entry for capitalised "Bob" from `PWOB` to `PWO*B` (there is an entry in `top-10000-english-words.json` for `"PWOB": "bob"`, and I'm currently assuming that this is for the verb "to bob", rather than the name "Bob")
- changes Typey-Type dictionary entry for capital "Ford", and changes the `TPO*RD` entry to mean `{^ford}` rather than "Ford", as per changes in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)
=> Fix capitalisation of some human names in Typey-Type dictionaries

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) would seem to have removed stroke `PWRET` for "breadth", so this PR:
- removes `PWRET` from `dict.json`
- changes the Typey-Type stroke for "breadth" to `PWR*ED`
=> Change stroke for "breadth" from PWRET to PWR*ED

dictionaries/top-10000-english-words.json
This PR proposes that for the word "picks", Typey-Type dictionaries should use easier-to-stroke `PEUBGS` over the current `PEUBGZ` stroke.
=> Use PEUBGS over PEUBGZ for "picks"

dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the stroke used for "kings" in Typey-Type dictionaries from `KEUPBGZ` to the easier-to-stroke `KEUPBGS`.
=> Change stroke used for "kings" in Typey-Type dictionaries

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) would seem to have changed the entry for the `HAPBGD` stroke from "hanged" to "handing".
Therefore, this PR proposes to:
- Change the mapping for `HAPBGD` from "hanged" to "handing"
- Change Typey-Type dictionaries to use multi-stroke `HAPBG/-D` for "hanged", since it is now the only stroke available for that word
=> Change entry for HAPBGD stroke from "hanged" to "handing"

dictionaries/top-10000-english-words.json
The `dictionaries/dict.json:16557` entry for "IDs" (`EUFPLT/TK-FPLT/-S": "IDs"`) is correct, but
https://github.com/didoesdigital/steno-dictionaries/blob/ef5681c357435ecfcf8da70121974b861d7eb5aa/dictionaries/top-10000-english-words.json#L9966
does not have the correct capitalisation, so this PR fixes that.
=> Fix capitalisation on 'IDs'

dictionaries/code.json, dictionaries/top-10000-english-words.json
The dictionaries currently have entries for "obj" in the following places:
https://github.com/didoesdigital/steno-dictionaries/blob/f98e522fd3637a7fe8b9f3cdf79544b15b25ff1c/dictionaries/code.json#L28
https://github.com/didoesdigital/steno-dictionaries/blob/ef5681c357435ecfcf8da70121974b861d7eb5aa/dictionaries/top-10000-english-words.json#L8372
However, Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) does not have a stroke entry for "obj", and the stroke `O*PBLG ` outputs as-is, so this PR proposes to change the stroke for "obj" to its finger-spelling (`O*/PW*/SKWR*`).
=> Change stroke for "obj" to its fingerspelling

dictionaries/top-10000-project-gutenberg-words.json
Changes the `"quitted"` entry stroke of `"KWEUT/-D"`, which currently outputs "quited" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), with the fingerspelling of the word "quitted".
Closes #61
=> Change entry for 'quitted' to its fingerspelling.

dictionaries/nouns.json, dictionaries/top-10000-english-words.json
Due to Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) not having an entry for the word "notre", and given that "notre" was _probably_ only included in [Google’s Trillion Word Corpus via Josh Kaufman's typing word list](https://didoesdigital.com/typey-type/support#credits) due to it being a part of the landmark/place name "Notre Dame", this PR proposes to give the "notre" entries their full context by changing them all to "Notre Dame".
Closes #58
=> Change 'notre' entries to 'Notre Dame'.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-english-words.json, dictionaries/top-10000-project-gutenberg-words.json
This PR fixes the (still-valid-in-Plover) mis-strokes brought up in #41. Specifically:
- Change stroke for `"fluid"` from `"THRAOUD"` to `"TPHRAOUD"`
- Change stroke for `"lenses"` from `"HREBSZ"` to `"HREPBSZ"`
(The stroke for `"fault"` had already been fixed, so no changes needed).
=> Fix mis-strokes for "fluid" and "lenses"

dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for the word "slept":
```json
"SHREPD": "slept",
"SHREPT": "slept",
```
Both of these strokes are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33P), but the stroke that appears in Typey-Type is:
https://github.com/didoesdigital/steno-dictionaries/blob/5ad75a255ea296068cacd89b05c30de93d5375c0/dictionaries/top-10000-project-gutenberg-words.json#L2047
I would posit that:
- `SHREPT` sounds like a _more_ correct stroke for "slept"
- If you don't need to reach for the steno "D" key for a correct stroke, then you shouldn't be made to
Therefore, this PR proposes to change the entry in `top-10000-project-gutenberg-words.json` for "slept" …
=> Change Typey-Type stroke for 'slept' from SHREPD to SHREPT

dictionaries/condensed-strokes.json
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the stroke `AO*EUD` is not present for the word "eyed".
All entries for "eyed" in other dictionaries are for the correct `KWRAOEUD` stroke, so I'm assuming that the condensed stroke was once correct, but now it is not, so this PR seeks to remove it so it does not appear in Typey-Type.
This does bring up a separate issue that about the current output for the stroke `AO*EUD`. `AO*EUD` outputs "ID" in all capitals, however, in the dictionaries, we have:
```
top-10000-project-gutenberg-words.json: "EUD": "ID",
dict.json: "AO*EUD": "ID",
```
The `EUD` stroke for "ID" is now incorrect, as it outputs "id" in lowercase. Happy to handle the changes needed to …
=> Remove incorrect condensed stroke of AO*EUD for 'eyed'

dictionaries/top-10000-project-gutenberg-words.json
Following up from #79, this PR corrects the output for the `EUD` from uppercase "ID" to lowercase "id".
=> Change output of EUD stroke from 'ID' to correct 'id'

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Fixes #81 by:
- moving `HRUFP` mis-stroke for "clutch" into `bad-habits.json`
- updating `top-10000-project-gutenberg-words.json` with correct stroke `KHRUFP` for "clutch"
=> Fix stroke for "clutch"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Move `EPBG` mis-stroke for "edge" into `bad-habits.json`.

dictionaries/bad-habits.json, dictionaries/briefs.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `briefs.json` and `top-10000-project-gutenberg-words.json` dictionaries, there is the following single-stroke entry for the word "capital":
https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/briefs.json#L63
https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L1312
However, it would seem that `KAPLT` is no longer a valid stroke for "capital" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33). It would seem that the stroke has changed to `KPAL`, which is not currently in any of the dictionaries. Therefore, this PR seeks to:
- Remove …
=> Change KAPLT stroke for "capital" to KPAL

dictionaries/top-10000-project-gutenberg-words.json
The two-stroke entry for "patiently" in `dict.json` is correct, but according to Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), there is no single-stroke entry for "patiently" (the only entry for "patiently" is `PAEURBT/HREU`).
The `top-10000-project-gutenberg-words.json` dictionary is the only place the incorrect entry appears, and so this PR seeks to just change that two the correct two-stroke entry.
=> Change incorrect 'patiently' single-stroke entry to correct two-stroke entry

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark SELGD for "secondly" as a mis-stroke. 

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark TEPGS stroke for 'tension' as mis-stroke.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark SKRAUGS stroke for 'concentration' as mis-stroke.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Fixes #107.
Note that the choice for the replacement stroke in the Gutenberg dictionary was a result of personal preference. `"A/PH*EUS": "amidst"` would also have been equally valid.
=> Mark 'Philly-shift' stroke A/PHEUTDZ for 'amidst' as a mis-stroke.

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
Fixes #108.
Note that the stroke for "tiding" depends on the orthography rules because it changes "tide" to "tiding".
=> Fix strokes for "tiding" and "tidings".

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` and `top-10000-project-gutenberg-words.json` dictionaries, the single-stroke entry for "independently" is:
```json
"PAEPBLT": "independently",
```
However, that stroke does not seem to exist at all in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33). The Plover single-stroke entry for "independently" is `P*EPBLT`.  Therefore, this PR seeks to:
- Add `"PAEPBLT": "independently"` to `bad-habits.json` to mark it as a mis-stroke
- Change the single-stroke entries for "independently" in `dict.json` and `top-10000-project-gutenberg-words.json` from `PAEPBLT` to `P*EPBLT`.
=> Change stroke for "independently"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), there is no entry for the stroke `PREGS` to mean "profession". Therefore, this PR aims to:
- Mark stroke `PREGS` for 'profession' as a mis-stroke in the dictionaries
- Change the Typey-Type stroke for it to the correct `PREFGS`
=> Mark stroke PREGS for 'profession' as a mis-stroke

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Change stroke for "remaining" to have elongated "ā" sound (`AEU`) and mark existing `RE/PHAEPBG` stroke as a mis-stroke.
Fixes #130.
=> Change stroke entry for "remaining" to have elongated "ā" sound

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Fixes #132.
- Remove "PRO/TPHUPBS/-D": "pronounced", from dict.json
- Remove "PRO/TPHUPBS/KWRAEUGS": "pronunciation", from dict.json
- Add "PRO/TPHUPBS/-D": "pronounced", to bad-habits.json
- Add "PRO/TPHUPBS/KWRAEUGS": "pronunciation", to bad-habits.json
- Change the "pronounced" entry in top-10000-project-gutenberg-words.json from
PRO/TPHUPBS/-D to PRO/TPHOUPBS/-D
=> Fix stroke entries for "pronounce" and "pronunciation"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Fixes #137.
Mark EUPB/TPAPT for "infant" as a mis-stroke as it drops the `B` for the "n" sound in "-fant".
=> Mark EUPB/TPAPT for "infant" as a mis-stroke

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark strokes for "intentions" that do not use full PB stroke for the "n" as mis-strokes

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark strokes for "indulgence" that use LS instead of LG for the "lj" sound as mis-strokes.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark stroke for "overwhelmed" that uses K instead of W when beginning "-whelm" as a mis-stroke.

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Fix entries containing "enchant" to use the full KH stroke for the "ch" sound. 

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark "inscrib*" words that do not use an S stroke as mis-strokes

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "heritage", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"HAR/TAPBLG": "heritage",
"HER/TAPBLG": "heritage",
"HERT/APBLG": "heritage",
```
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "heritage" is:
https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L8961
The "a" sound in the stroke for "heritage" looks like a mis-stroke to me, so this PR proposes:
- Removing `"HAR/TAPBLG": "heritage"` from `dict.json`
- Adding `"HAR/TAPBLG": "heritage""` to `bad-habits.json`
- In …
=> Change stroke for "heritage" to use "e" sound, rather than "a".

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "clerical", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"KHRAOERBL/K-L": "clerical",
"KHRER/K-L": "clerical",
"KHRER/KAL": "clerical",
"KHRERBG/A*L": "clerical",
"KHRERBG/K-L": "clerical",
"KRER/K-L": "clerical",
```
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "clerical" is:
https://github.com/didoesdigital/steno-dictionaries/blob/fe5055bfcf402bf7937ec74143fc18934e207788/dictionaries/top-10000-project-gutenberg-words.json#L9027
`"KRER/K-L": "clerical"` without the `H` stroke to make the `HR` "l" sound looks like a mis-stroke to me, so this PR proposes:
- …
=> Add `H` stroke to entry for "clerical"

dictionaries/top-10000-project-gutenberg-words.json
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "percentage" is:
https://github.com/didoesdigital/steno-dictionaries/blob/fb0fd2fb03b97163c8147363a66ad54130b8e427/dictionaries/top-10000-project-gutenberg-words.json#L9551
I don't think this stroke is a mis-stroke, but I would like to propose that `PERS/APBLG` with an `S` stroke is a more intuitive entry pronunciation-wise, and it would be good to have Typey Type use it.
=> Have Gutenberg dictionary use `PERS/APBLG` stroke for "percentage"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
=> Mark stroke for "harmonious" without a leading `H` as a mis-stroke.

dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "occupy", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"OBG/KAOU/PEU": "occupy",
"OBG/KWRAOU/PEU": "occupy",
"OBG/KWRU/PEU": "occupy",
"OBG/PAOEU": "occupy",
"OBG/PEU": "occupy",
```
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "occupy" is:
https://github.com/didoesdigital/steno-dictionaries/blob/e9408eec8e47755e728bb1d68fce29a58ba0f121/dictionaries/top-10000-project-gutenberg-words.json#L3935
Out of all the outlines listed above, `"OBG/PAOEU": "occupy"` with the long "ī" seems like the most correct pronunciation-wise, but since it's the only one that _does_ …
=> Have Gutenberg dictionary use `OBG/PAOEU` outline with a long "ī" for "occupy"

dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "successor", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"SUBG/SES/O*R": "successor",
"SUBG/SES/SOR": "successor",
"SUBG/SESZ/SOR": "successor",
```
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "successor" is:
https://github.com/didoesdigital/steno-dictionaries/blob/e9408eec8e47755e728bb1d68fce29a58ba0f121/dictionaries/top-10000-project-gutenberg-words.json#L5121
I wouldn't argue that `"SUBG/SES/O*R": "successor"` is a mis-stroke, but this PR proposes that `"SUBG/SES/SOR": "successor"` is a better fit spelling-wise (with a "double-s"), and it doesn't require …
=> Change outline used for "successor" in Gutenberg to one without an asterisk.

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add in the `K*ELT` Plover outline for "kettle" to `dict.json`, and use it in the Gutenberg dictionary.
=> Add new Plover single-stroke outline for "kettle"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s `"RARLD": "regardless"` outline, and prefer it in Typey-Type due to not having to stroke `DZ`.
=> Add new `RARLD` outline for "regardless" and have the Gutenberg dictionary use it.

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s single-stroke `"KHROFL": "colossal"` outline, and prefer it in Typey-Type.
=> Add new Plover `KHROFL` outline for "colossal" and have the Gutenberg dictionary use it.

dictionaries/nouns.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "flutter", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"TPHRUT/*ER": "flutter",
"TPHRUT/ER": "flutter",
"TPHRUT/TER": "flutter",
```
In the `top-10000-project-gutenberg-words.json` and `nouns.json` dictionaries, the stroke used for "flutter" is:
https://github.com/didoesdigital/steno-dictionaries/blob/cd9048411754dddb3c3e043134b2f8e85f952908/dictionaries/top-10000-project-gutenberg-words.json#L8687
https://github.com/didoesdigital/steno-dictionaries/blob/cd9048411754dddb3c3e043134b2f8e85f952908/dictionaries/nouns.json#L447
Since `"TPHRUT": "flutter"` is not in `dict.json`, nor is it in Plover, …
=> Fix errors with outline for "flutter", and add "-er" suffixes.

dictionaries/dict.json, dictionaries/nouns.json, dictionaries/top-10000-project-gutenberg-words.json
It looks like the `TKPWHREUT` outline for "glitter" is either a typo or was changed in a later release of Plover (or perhaps it was a condensed stroke since it wasn't originally entered into `dict.json`...?), so this PR proposes to change `TKPWHREUT` outlines for the now-correct `TKPWHREURT`.
=> Add `TKPWHREURT` outline for "glitter"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover's `KHAOEUPBZ` outline for "Chinese", and have it be used in the Gutenberg dictionary.
=> Add Plover `KHAOEUPBZ` outline for "Chinese"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a `TPURPB/-D` condensed stroke for "furnished" to mirror the `TPURPB` outline for "furnish".
It also proposes to use it in the Gutenberg dictionary as the current `TPURPB/EURBD` outline, while valid in Plover and not looking like a mis-stroke pronunciation-wise, makes you essentially stroke "furnish-ished".
=> Add `TPURPB/-D` condensed stroke for "furnished"

dictionaries/top-10000-project-gutenberg-words.json
I think that "main" and "tain" both (generally) have a long "ā" vowel sound, so this PR proposes to change the entry in Gutenberg to make both those vowel sounds the same in the outline for "maintain".
I'm hesitant to consider `PHEUPB/TAEUPB` a mis-stroke due to potential human accent variations, but I do think `PHAEUPB/TAEUPB` sounds _more_ correct.
=> Change "a" vowel in "maintain" outline to be an "ā"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the "obey" outline in Gutenberg to give it a "ō" vowel.
I'm hesitant to consider `O/PWAEU` a mis-stroke due to potential human accent variations, but I do think `OE/PWAEU` sounds _more_ correct in this case.
=> Change "o" vowel in "obey" outline to be an "ō"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `KUPB/SEUL` as a mis-stroke due to the missing "o" vowel in "council", and have the Gutenberg dictionary use `KOUPB/SEUL` as the most accurate outline.
=> Mark `KUPB/SEUL` for "council" as a mis-stroke due to missing the "o" vowel

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover `TPH-FPBT` outline for "infinite", and use it in the Gutenberg dictionary.
=> Add Plover `TPH-FPBT` outline for "infinite"

dictionaries/top-10000-project-gutenberg-words.json
`O/PWAOED/KWREPBS` does not look like a mis-stroke to me, but I think that `OE/PWAOED/KWREPBS` with an "ō" vowel is a bit more correct pronunciation-wise, so this PR proposes to change the entry in Gutenberg to use it.
=> Change "obedience" outline used in Gutenberg dictionary to long "ō" vowel.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
`SROL/TKPWAR` for "vulgar" seems like a mis-stroke to me, so this PR proposes to move it to `bad-habits.json` and have the Gutenberg dictionary use the other `SRUL/TKPWAR` Plover outline for "vulgar".
=> Mark `SROL/TKPWAR` for "vulgar" as a mis-stroke due to the "o" vowel

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
`PWOEPB/PART` outputs "bone part" in vanilla Plover, so this PR proposes to change the outline for "Bonaparte" to be Plover's `PWOEPB/PA*RT` entry.
=> Fix outline for "Bonaparte" to be Plover's entry of `PWOEPB/PA*RT`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "declaration", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"TKE/KHRA/RAEUGS": "declaration",
"TKE/KHRAR/AEUGS": "declaration",
"TKEBG/HRA/RAEUGS": "declaration",
"TKEBG/HRAEUGS": "declaration",
"TKEBG/HRAR/AEUGS": "declaration",
"TKELG/RAEUGS": "declaration",
"TKERBG/HRAEUGS": "declaration",
```
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "declaration" is:
https://github.com/didoesdigital/steno-dictionaries/blob/6fcda7395ef4b30925638d729ec5b53305911a81/dictionaries/top-10000-project-gutenberg-words.json#L4310
I'm not sure what rules the `TKELG/RAEUGS` is …
=> Mark `TKELG/RAEUGS` outline for "declaration" as a mis-stroke.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s output for the `SHRA*EUGS` outline is now "legislation", and not "insulation".
Therefore, this PR proposes to fix this issue, and have the Gutenberg dictionary use `SHRA*EUGS` for "legislation".
If `SHRA*EUGS` isn't desired so much in Typey Type since it's asterisked, then I would propose `HREGT/SHRAEUGS` to be a better match for "legislation" than the current `HREGT/SHUPB`.
=> Change `dict.json` output for `SHRA*EUGS` to "legislation"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) has a `TPA*BG` outline for "faculty", so this PR proposes to add it to `dict.json`, and use it as the "faculty" outline in the Gutenberg dictionary.
=> Add Plover `TPA*BG` outline for "faculty"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
I don't think any of the current outlines for "seldom" in the dictionary are mis-strokes, so this PR just proposes to add Plover's `SELD` outline, and use it in Typey-Type.
=> Add Plover `SELD` outline for "seldom" and use it in the Gutenberg dictionary

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "offensive", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):
```json
"O/TPEPBS/*EUF": "offensive",
"OE/TPEPBS/EUF": "offensive",
"OFPBS/*EUF": "offensive",
```
In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "offensive" is:
https://github.com/didoesdigital/steno-dictionaries/blob/e9408eec8e47755e728bb1d68fce29a58ba0f121/dictionaries/top-10000-project-gutenberg-words.json#L5243
I don't think that any of these are mis-strokes, but since the outlines for the `{^ive}` suffix cover both `*EUF` and `EUF`, it would seem to make sense to me to use the asterisk-less version where …
=> Add condensed stroke for "offensive".

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a condensed stroke for "politeness" that uses the `-PBS` {^ness} suffix, and use it in the Gutenberg dictionary and Typey Type.
=> Add condensed stroke for "politeness" that uses the `-PBS` {^ness} suffix

dictionaries/top-10000-project-gutenberg-words.json
In the current `dict.json` file, there are the following strokes for "Rebecca":
```json
"RE/PWABG/KA": "Rebecca",
"RE/PWEBG/KA": "Rebecca",
```
This PR proposes to change the Gutenberg outline for "Rebecca" to use an `E`, rather than `A` stroke. I don't necessarily think that `RE/PWABG/KA` is a mis-stroke, but `RE/PWEBG/KA` reads more correctly to me.
=> Change vowel from `A` to `E` in outline for "Rebecca".

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
The following outlines for "holiday" seem like mis-strokes to me:
- `HOL/TKEU` ("holdi")
- `HOL/TKEU/TKAEU` ("holdiday")
So, this PR proposes to move them to `bad-habits.json`, and have `HOL/TKAEU` with the long "ā" vowel be considered the more accurate pronunciation in the Gutenberg dictionary.
=> Mark `HOL/TKEU` and `HOL/TKEU/TKAEU` outlines for "holiday" as mis-strokes

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
It looks like the `PORT/TKWAOES` outline for "Portuguese" is missing the `P` stroke in the `TKPW` "g" sound.
So, this PR proposes to consider it a mis-stroke, and have the Gutenberg dictionary use `PORT/TKPWAOES`.
=> Mark `PORT/TKWAOES` outline for "Portuguese" as a mis-stroke

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s single-stroke `HRARBT` outline for "elaborate", and have the Gutenberg dictionary use it.
=> Add Plover single-stroke `HRARBT` outline for "elaborate"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) outputs "Sara", without an "h", for the `SA/RA` outline.
So, this PR proposes to fix the current `SA/RA` entry, and have the Gutenberg dictionary use `SAEU/RA` for "Sarah".
The other Plover outline for "Sarah", `SAEUR/KWRA`, reads a bit weird to me ("Saryah"?), so I'd also be happy to mark that as a mis-stroke, but I'm not sure if I'm just not aware of a steno rule.
=> Mark `SA/RA` outline for "Sarah" as a mis-stroke as it outputs "Sara".

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the outline used in Gutenberg for "triumphant" to have a long "ī" vowel sound. I don't think any English pronunciations of "triumphant" use a short "i".
=> Change outline used in Gutenberg for "triumphant" to have long "ī" vowel sound

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change outline for "Satan" to have a long "ā" vowel, and mark the outline with a short "a" vowel as a mis-stroke 🤘
=> Change outline for "Satan" to have a long "ā" vowel

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `KA/TAOED/RAL` outline for "cathedral" as a mis-stroke due to missing an `H`, and prefer `KA/THAOED/RAL` in the Gutenberg dictionary.
=> Mark `KA/TAOED/RAL` outline for "cathedral" as a mis-stroke

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark the `SREFT/SRAL` outline for "festival" as a mis-stroke due to beginning with an `SR` "v" sound, and prefer the `TPEFT/SRAL` outline in the Gutenberg
dictionary.
=> Mark `SREFT/SRAL` outline for "festival" as a mis-stroke

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s `STPEUBG` outline for "fantastic", and have the Gutenberg dictionary use it.
=> Add Plover's `STPEUBG` outline for "fantastic"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) has a `THA*PBG/-FL` outline for "thankful", but for some reason it doesn't have a `THAPBG/-FL` outline, which outputs "thankful" as expected.
So, this PR proposes to add it as a condensed stroke and have the Gutenberg dictionary use it due to, in at least my opinion, "thank-ful" being a better word division than "than-kful".
=> Add `THAPBG/-FL` condensed stroke for "thankful"

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json, dictionaries/proper-nouns.json, dictionaries/top-10000-project-gutenberg-words.json
Due to outline `PHAD/APL` outputting uppercase "Madam" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), it seems like there is no outline option for lowercase "madam". 
So, in order to keep current lowercase "madam" entries, change the outlines to "madam"'s fingerspelling.
Closes #317.
=> Add fingerspelling entry for lowercase "madam"

dictionaries/condensed-strokes.json
This PR only proposes to add `"TPRAOUT/-LS": "fruitless"` as a condensed stroke. It's not necessarily better than `"TPRAOUT/HRES": "fruitless"`, the current outline used in Gutenberg, and so no change is proposed there.
Closes #294.
=> Add "TPRAOUT/-LS": "fruitless" condensed stroke.

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
Although Plover's outline for "captains" is `KAPT/EUPBS`, since stroking just `KAPT` outputs "captain", this PR proposes to add a condensed stroke that just adds `-S` to that, and use it in the Gutenberg dictionary, rather than "captain-ins".
=> Add `KAPT/-S` condensed stroke for "captains"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `APBGT/WAER` outline for "sanctuary" as a mis-stroke due to missing `S` at the beginning (it's the only outline in the set for "sanctuary" that is missing it). It also proposes to prefer `SAPBGT/WAER` in the Gutenberg dictionary.
=> Mark `APBGT/WAER` outline for "sanctuary" as a mis-stroke

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to just change Gutenberg dictionary outline for "catastrophe" to prefer `KATS/TROEF` over the current `KATS/TROER`. I think the "f" sound in "catastrophe" is a more prominent sound than its "r" in helping to remember the outline.
=> Change Gutenberg dictionary outline for "catastrophe" to `KATS/TROEF`

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover single-stroke `STREUFBG` outline for "asterisk" to `dict.json`, and have the Gutenberg dictionary prefer it over `AS/TREUS`.
=> Add Plover `STREUFBG` outline for "asterisk"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outline for "handwriting" to have a long "ī" vowel sound as I think this is more intuitive than the short "i" vowel. I don't necessarily think the short "i" is a mis-stroke, so there's no proposal to move it to `bad-habits.json`.
=> Change vowel sound in Gutenberg outline for "handwriting" to long "ī"

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the only outline for "historians" specified is `PHEUFT/KWRAPBS`. I find this a bit strange since:
- I'm not sure where the `P` prefix comes from
- There is a valid outline for `"HEUFT/KWRAPB": "historian"`
Stroking `HEUFT/KWRAPBS` outputs "historians" as expected, so this PR proposes to:
- Add `"HEUFT/KWRAPBS": "historians"` as a condensed
- Mark current `"PHEUFT/KWRAPBS": "historians"` outline as a mis-stroke
- Change the Gutenberg dictionary to use `"HEUFT/KWRAPBS": "historians"`
=> Add `HEUFT/KWRAPBS` condensed stroke for "historians"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to remove the `SPEPBD/TAOURS` condensed stroke for "expenditures", as it outputs "spend tours" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33).
The Plover `EBGS/PEPBD/KHURS` outline sounds like the "most correct" outline for "expenditures" to me, so use that in the Gutenberg dictionary instead.
=> Remove `SPEPBD/TAOURS` condensed stroke for "expenditures"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the vowel sound in outline for "potent" to a long "ō" in the Gutenberg dictionary.
Following on from [this comment](https://github.com/didoesdigital/steno-dictionaries/pull/340#issuecomment-616036605), I'm refraining from also proposing to make `PO/TEPBT` a mis-stroke :)
=> Change vowel sound in outline for "potent" to long "ō" in Gutenberg

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s `AOUT/TKAEUTD` outline for "outdated" to `dict.json` and prefer it in the Gutenberg dictionary over `AOUTD/TKAEUTD`.
=> Add Plover `AOUT/TKAEUTD` outline for "outdated"

dictionaries/top-10000-project-gutenberg-words.json
This PR simply proposes to prefer the `HRES/HREU` outline for "Leslie" in the Gutenberg dictionary to avoid a (subjectively unnecessary) reach for the `Z` key.
=> Prefer the `HRES/HREU` outline for "Leslie"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add `SREUFD/HREU` outline as a condensed stroke for "vividly" and have the Gutenberg dictionary prefer it over the current Plover `SREUF/TKHREU`.
I think it makes a more logical division of the word ("vivid-ly" vs "viv-dly"), and also makes a nice construction from current outlines and suffixes (`SREUFD` for "vivid", `HREU` for "{^ly}").
=> Add `SREUFD/HREU` outline as a condensed stroke for "vividly"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover's `TKOPLT` outline for "dominant" and use it in the Gutenberg dictionary.
=> Add Plover `TKOPLT` outline for "dominant"

dictionaries/top-10000-project-gutenberg-words.json
I wouldn't consider the `SRA/RAPB/TKA` outline for "veranda" a mis-stroke, but I think `SRE/RAPB/TKA` is _more_ correct, so this PR proposes to use it in the Gutenberg dictionary.
=> Use outline with "e" vowel (`SRE/RAPB/TKA`) for veranda in Gutenberg dictionary

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes an ergonomic change to use `POEUS/TPHOUS` over `POEUZ/TPHOUS` in the Gutenberg dictionary. I think that both outlines are as correct as each other, but if one can prevent a reach to `Z`, then that's the one I would at least prefer.
=> Change outline used for "poisonous" in Gutenberg to use an `S` over `Z`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark the "custody" outline `KUFD/TEU` ("cusdoty") as a mis-stroke, and instead prefer the Plover `KUFT/TKEU` outline as being more accurate.
=> Mark `KUFD/TEU` outline for "custody" as a mis-stroke

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer the `PER/SPRAEUGS` outline for "perspiration" in the Gutenberg dictionary over `PERP/RAEUGS` ("per-sprātion" vs "perp-rātion").
I don't necessarily think `PERP/RAEUGS` looks wrong, so there is no current intention to mark it as a mis-stroke.
=> Prefer `PER/SPRAEUGS` outline for "perspiration" in the Gutenberg dictionary

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer the explicit addition of an ending `A` stroke for the "Cleopatra" outline in the Gutenberg dictionary (`KHRAOE/PAT/RA`).
=> Prefer the explicit addition of ending `A` stroke for "Cleopatra" (`KHRAOE/PAT/RA`)

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer the stressed long "ī" over short "o" vowel in outline for "biography".
I think "bīg-fi" sounds closer in pronunciation to "biography" than "bog-fi", but I don't necessarily think `PWOG/TPEU` reads as a mis-stroke, so the PR only proposes to change the Gutenberg entry.
=> Prefer stressed long "i" over short "o" vowel in outline for "biography" (`PWAOEUG/TPEU`)

dictionaries/top-10000-project-gutenberg-words.json
Similar to "Owen" in #340, this PR proposes to change the outline for "omen" in the Gutenberg dictionary to have a long "ō" vowel (without marking the short vowel version as a mis-stroke).
=> Prefer long "ō" vowel in outline for "omen" in the Gutenberg dictionary

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s `SROEBGS` outline for "vocation", and prefer it in the Gutenberg dictionary over `SRO/KAEUGS`.
=> Add Plover `SROEBGS` outline for "vocation"

dictionaries/condensed-strokes.json
Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) currently only has one outline for "denote", with a long "ē" vowel: `TKAOE/TPHOET`. This is not wrong at all, so this PR only proposes to add `TKE/TPHOET` outline as a condensed stroke for "denote".
=> Add `TKE/TPHOET` outline as a condensed stroke for "denote"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer addition of an explicit "l" (`HR`) stroke in outline for "vocabulary" in the Gutenberg dictionary. 
To me, `SROEBG/PWHRAER` ("vōc-blary") sounds closer to "vocabulary" than `SROEBG/PWAER` ("vōc-bary"), but I wouldn't go so far as to mark the latter as a mis-stroke.
=> Prefer addition of explicit "l" (`HR`) stroke in outline for "vocabulary"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer the long "ē" vowel and division of word syllables of the `AUS/TAOER` outline for "austere" in the Gutenberg dictionary, over the current `AU/STER` outline.
=> Prefer `AUS/TAOER` outline for "austere"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer a long "ē" vowel in outline for "albeit" in the Gutenberg dictionary.
I think `AL/PWAOET` ("al-bēt") sounds closer to "albeit" than `AL/PWAEUT` ("al-bait").
=> Prefer long "ē" vowel in outline for "albeit" (`AL/PWAOET`) in Gutenberg

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
- Prefer long "i" vowel outline in Gutenberg dictionary (`PHULT/PHRAOEU`)
- Mark `PHRULT/PHRAOEU` outline for "multiply" as a mis-stroke due to extraneous `R` stroke in "mult"
=> Change vowel sound in outline for "multiply" to long "ī" (`PHULT/PHRAOEU`)

dictionaries/nouns.json, dictionaries/top-10000-project-gutenberg-words.json
Plover currently does not have an "official" outline for "methinks", and the original `PHE/THEUS` outline outputs "me thinks" with a space. So, this PR proposes to change it to `PHE/TK-LS/THEUS` to ensure that "me" and "thinks" stick together. I couldn't figure out any better outline, but I'm more than happy to change it to something else!
=> Change outline for "methinks" in dictionaries to be `PHE/TK-LS/THEUS`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `WHEURL/WEUPD` outline for "whirlwind" as a mis-stroke due to missing a `B` stroke in its "n" sound, and prefer `WHEURL/WEUPBD` in the Gutenberg dictionary.
=> Mark `WHEURL/WEUPD` outline for "whirlwind" as a mis-stroke

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s `SHOEUD` outline for "shadow", and use it in the Gutenberg dictionary.
=> Add Plover `SHOEUD` outline for "shadow"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer a long "ō" vowel in the outline for "Hanover" in the Gutenberg dictionary.
=> Prefer long "o" vowel in outline for "Hanover" in Gutenberg dictionary.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
The `TERL` outline now outputs "teller", rather than "material" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), so this PR proposes to:
- Change `TERL` entry in `dict.json` to reference "teller"
- Add `TERL` for "material" to `bad-habits.json`
- Use `TAOERL` outline in the Gutenberg dictionary for "material"
=> Change outline for "material" to `TAOERL`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to prefer `SHRERPBLG` outline for "soldier", and mark the `SHRERPBL` outline for "soldier" as a mis-stroke due to missing a `G` stroke in the `PBLG` "j" sound.
=> Prefer `SHRERPBLG` outline for "soldier"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33)'s `HR*ES` outline for "lest", and have the Gutenberg dictionary prefer it over `HRES/*T`.
=> Add Plover `HR*ES` outline for "lest"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to have the Gutenberg dictionary prefer `WRAOEUR` outline with long "ī" sound for "writer" to match word pronunciation (but not consider the orthographic entry a mis-stroke).
=> Have Gutenberg dictionary prefer `WRAOEUR` outline with long "ī" sound for "writer"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark the `EPDZ` outline for "ends" as a mis-stroke due to missing the `B` stroke in the `PB` "n" sound. As a result of this, have the Gutenberg dictionary prefer the `EPBDZ` outline for "ends".
=> Mark `EPDZ` outline for "ends" as a mis-stroke, prefer `EPBDZ`

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to have the Gutenberg dictionary prefer a long "ī" sound in outline for "violent" (`SRAOEUPBLT`) rather than what looks like an orthographic entry with inversion(?) (`SROEUPBLT`).
=> Have the Gutenberg dictionary prefer a long "ī" sound in outline for "violent" (`SRAOEUPBLT`)

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to fix (what looks like) a typo in Gutenberg dictionary for "contained" outline. `TAEUPBG` ("tained") -> `KAUPB/TAEUPBD` ("contained").
`TAEUPBG` has a named entry in `dict.json` as "tained", and `TAEUPBG` for "contained" does not have an entry in any of the other dictionaries.
=> Fix typo(?) in Gutenberg dictionary for "contained" outline.

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to fix the Gutenberg outline for "frightened" by adding a missing `F` to make `TPRAOEUFPBD`. `TPRAOEUPBD` for "frightened" doesn't appear in any of the other dictionaries, and isn't in Plover, so perhaps this was a typo?
=> Fix Gutenberg outline for "frightened": add a missing `F` to make `TPRAOEUFPBD`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes a change that goes a bit against the general rules of these dictionaries:
Mark `KAEULT` outline for "indicate" as a mis-stroke due to potentially confusing use of `L` stroke (it confused me, anyway: "indicalte"?), and prefer `KA*EUT` instead. Even though `KA*EUT` uses an asterisk, I think it more accurately represents the pronunciation of "indicate" and is easier to remember.
=> Mark `KAEULT` outline for "indicate" as a mis-stroke, prefer `KA*EUT`

dictionaries/top-10000-project-gutenberg-words.json
The current outline for "western" in the Gutenberg dictionary outputs to "Western" with a capital "W", so this PR proposes to change this to the outline for lowercase "western".
Same for the outline for "eastern".
=> Fix casing for outlines for "western" and "eastern" used in Gutenberg dictionary.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to fix the "Saturday" outline: the current one, `SAET`, outputs "seat". So, fix that outline and prefer the `SATD` outline for "Saturday" in the Gutenberg dictionary (chosen over `SARD` since I personally found it more intuitive to stroke: you have to make the reach for `D` regardless of which of the two outlines you use).
=> Fix outline for "Saturday": `SAET` outputs "seat", change to `SATD`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the entry for the `PORPLS` outline to specify an output of "performs", rather than "performance" as per behaviour in  Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33).
As a result of this, also change the Gutenberg dictionary entry for "performance" to use the `P-FRPBS` outline, which is my favoured option.
=> Change entry for `PORPLS` outline to "performs" rather than "performance"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to give the Gutenberg dictionary outline for "newspaper" a long "ū" vowel sound to more accurately reflect the vowel in "news". I keep on pronouncing "nup" (as in "yep"/"nup") in my head 😆
=> Give Gutenberg outline for "newspaper" a long "ū" vowel sound

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the outline for "wearing" used in the Gutenberg dictionary to match with the `WAER` outline for "wear". `WAURG` ("wawring"?) looks a bit to me like a mis-stroke, but I'm guessing there is an accent that pronounces it that way, so I'm happy to leave it be.
=> Change outline for "wearing" to `WAERG`

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to fix the Gutenberg dictionary outline for "i.e." to the correct two-stroke `AOEU/KWRAOE`: the current `KWRO*EU` outline outputs "i.e.,". with a comma.
=> Fix Gutenberg dictionary outline for "i.e." to `AOEU/KWRAOE`

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to make some changes, mostly to the Gutenberg dictionary, to outlines where there is no issue with the current outline, but I subjectively think another outline is better, some of which are new outlines added to `dict.json`. Details are in each commit.
=> Outline preference proposals

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark the `STOERPL` outline for "storm" as a mis-stroke as it now outputs "stormy". As a result of this, prefer usage of single-stroke `STOERPL` over `STOR/PH*EU` in
the Gutenberg dictionary.
=> Mark `STOERPL` outline for "storm" as a mis-stroke

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover single-stroke outline `TP*ERT` for "feather" to `dict.json`, and have the Gutenberg dictionary prefer it.
=> Add Plover `TP*ERT` outline for "feather"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the outline for "casual" used in Gutenberg dictionary to `KARBL` to better match the word pronunciation ("cashl" vs "keasl").
=> Change outline for "casual" used in Gutenberg dictionary to `KARBL`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `TKRAFL` for "gravel" as a mis-stroke (even though it's a Plover dictionary outline) due to missing the `PW` strokes in the `TKPW` "g" sound. As a result of this, it also proposes to have the Gutenberg dictionary prefer the `TKPWRAFL` outline.
=> Mark `TKRAFL` for "gravel" as a mis-stroke due to missing the `PW` in "g" sound.

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outline for "retirement" to `RAO*EURPLT` to more accurately reflect word pronunciation (and for whatever reason, I found this outline more natural to stroke than the current `RAO*EUPLT`).
=> Change Gutenberg outline for "retirement" to `RAO*EURPLT`

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
There is a Plover outline for "cum" (`KR*UPL`), so this PR proposes to add it to `dict.json` and have the Gutenberg dictionary use it.
=> Add Plover outline for "cum"

dictionaries/top-10000-project-gutenberg-words.json
Outline `PHROER` for "employer" comes from a personal Di brief that is not in Plover (it outputs "PHROER" as-is):
https://github.com/didoesdigital/steno-dictionaries/blob/47fabaf8affaa8fdb472c02d5b97232396d2afb7/dictionaries/di-briefs.json#L10
Therefore, this PR proposes to change the Gutenberg dictionary to use Plover outline `PHROEUR` instead.
=> Change Gutenberg outline for "employer" to `PHROEUR`

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to fix the `dict.json` outline for "pigs" that has an unneeded extra space (I'm assuming this was a typo...?), and have `PEUGZ` be the preferred outline for "pigs" in the Gutenberg dictionary as I think it's a better match pronunciation-wise ("pigz" vs "pēgs").
=> Use `PEUGZ` for "pigs" in Gutenberg dictionary

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
The outline `KHAOER/*ER` for "clearer" is missing a `R` stroke in the `HR` "l" sound, so this PR proposes to mark it as a mis-stroke. As a result of this, also have the Gutenberg dictionary prefer `KHRAOER/*ER` for "clearer".
=> Mark `KHAOER/*ER` for "clearer" as a mis-stroke

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Outline `TOFRB` for "torch" is missing a `P` stroke for the `FRPB` "rch" sound, so this PR proposes to mark it as a mis-stroke. As a result of this, have the Gutenberg dictionary prefer `TOFRPB` for "torch".
=> Mark `TOFRB` for "torch" as a mis-stroke.

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to have the Gutenberg dictionary prefer the `SAOERPB` outline for "senior" to place more emphasis on the long "ē" sound of the word pronunciation. Personally, I think it's a better match ("sēnr" vs "soinr").
=> Have Gutenberg dictionary prefer `SAOERPB` outline for "senior"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `AL` for "Al" as a mis-stroke since `AL` is used for lowercase "al".
Therefore, it also proposes to change the `dict.json` entry for outline `AL` to be "al", and change the outline used for "Al" in the Gutenberg dictionary to be `AL/AL`.
=> Mark `AL` for "Al" as a mis-stroke since it outputs "al".

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outline used for "Wright" to `WRAOEUGT` to more accurately match word pronunciation (with the bonus of it still being single-stroked and it doesn't have to use an asterisk).
=> Change Gutenberg outline used for "Wright" to `WRAOEUGT`

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover `EURS` outline for "IRS" to `dict.json`, and have the Gutenberg prefer it since it's single-stroke and easier to remember.
=> Add Plover `EURS` outline for "IRS"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outline for "restaurant" to `STRAUPBT` to better match its word pronunciation.
=> Change Gutenberg outline for "restaurant" to `STRAUPBT`.

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a condensed stroke for "perils" `PER/EUL/-S` and have the Gutenberg dictionary use it. The original outline used for "perils", `P*ERL/-S`, outputs "Perls".
=> Add condensed stroke for "perils" `PER/EUL/-S` and have the Gutenberg

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
The outline `PHAOUPBS` outputs "menus" rather than "municipal", so this PR proposes to:
- change the `dict.json` entry to reflect that
- mark `PHAOUPBS` for "municipal" as a mis-stroke
- have the Gutenberg dictionary prefer `PHAOUPBS/PAL` for "municipal".
=> Change "municipal" outline to `PHAOUPBS/PAL`

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outline for "dreamy" to remove the asterisk, and leverage the `TKRAOEPL` outline for "dream". Personally, I also think it's a better division of the word ("dream-y" vs "drea-my").
=> Change Gutenberg outline for "dreamy" to `TKRAOEPL/KWREU`

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to have the Gutenberg dictionary prefer a long "ō" vowel in outline for "lone".
=> Change "lone" outline to `HROEPB` with long "ō"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a `HRAEU/PWOUR/-D` condensed stroke for "laboured", and have the Gutenberg dictionary prefer it.
It would seem that this entry does not need to be dependent on the AU dictionaries. Also, even if it is, when stroking this in Typey Type, the outline ends up finishing before you can stroke the final `A*U` suffix.
=> Add `HRAEU/PWOUR/-D` condensed stroke for "laboured"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a `TPHO*TS` condensed stroke for "knots", and have the Gutenberg dictionary prefer it over the two stroke equivalent.
=> Add `TPHO*TS` condensed stroke for "knots".

dictionaries/dict-en-AU-with-extra-stroke.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add an `O*ERD/A*U` AU outline for "odour", based on the `O*ERD` outline for "odor", and have the Gutenberg dictionary prefer it.
=> Add `O*ERD/A*U` AU outline for "odour", based on `O*ERD` for "odor"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to:
- Add the Plover `HEPB/RET/TA` outline for "Henrietta", and have the Gutenberg dictionary prefer it over fingerspelling
- Have the Gutenberg dictionary prefer the current AU dictionary outline of `HOLT/A*U` over fingerspelling
=> Change fingerspelled names to outlines

dictionaries/dict-en-AU-with-extra-stroke.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to have Gutenberg dictionary prefer the "ta" outline from `dict-en-AU-with-extra-stroke.json` over `dict-en-AU-vocab.json`.
I'm a bit conflicted over this, because it's not possible to know in advance which of the AU dictionaries a student is going to use while doing Typey Type exercises. Personally, I use the `dict-en-AU-with-extra-stroke.json` dictionary, and many of the other AU-based strokes that show up in Typey Type lean more into that dictionary than `dict-en-AU-vocab.json`, which I think by itself justifies this change.
The way to make it all neutral, of course, is to simply change this entry to be fingerspelling, which I'd be okay with as well.
=> Have Gutenberg dictionary prefer the "ta" outline from `dict-en-AU-with-extra-stroke.json`

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark the `TPWREUFPL` outline for "organism" as a mis-stroke due to missing the `K` stroke in the `TKPW` "g" sound. As a result of this, it proposes to also have the Gutenberg dictionary prefer `TKPWREUFPL` for "organism".
=> Mark `TPWREUFPL` outline for "organism" as a mis-stroke.

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
=> Uppercase outline for "ESP" in Gutenberg dictionary.

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outlines for:
- "atoms" to `AT/OPLS`
- "mouths" to a new condensed stroke `PHO*UT/-S`
because of the high difficulty in stroking `-TSZ` without also hitting `D`.
There are many more outlines in `dict.json` that end in `-TSZ`, but these are the only two I could find in the Gutenberg dictionary.
=> Change Gutenberg outlines with `-TSZ`

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover `HEFPL` outline for "helpful", and have the Gutenberg dictionary prefer it over the current asterisked `H*EFL`.
=> Add Plover `HEFPL` outline for "helpful" and have the Gutenberg prefer it.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark `"AOUFRTS": "University"` as a mis-stroke as `AOUFRTS` outputs "universities" in Plover.
As a result of this, it also proposes to have the Gutenberg dictionary prefer the `AOUFRTS` outline for "universities" over `AO*UFRTS` (which is incorrect anyway as it outputs capitalised "Universities").
=> Mark `"AOUFRTS": "University"` as a mis-stroke as `AOUFRTS` outputs "universities"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
The current outline for "Thomson", `THOPLS/O*PB`, outputs "Thomason". There is no other named Plover entry for "Thomson", so this PR proposes to change the entry to fingerspelling in lieu of any other potential condensed stroke being found/created.
=> Change non-Plover outlines to fingerspelling.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to mark the `TPHOEGT` outline for "next to" as a mis-stroke, as it now outputs "noting".
Also, have the Gutenberg dictionary prefer `TPHOEGT` for "noting" over the asterisked version `TPHO*EGT`.
=> Mark `TPHOEGT` outline for "next to" as a mis-stroke.

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to give the Gutenberg outline entry for "savings" a long "ā" vowel, `SAEUFGS`, to more accurately match its word pronunciation.
=> Give Gutenberg outline entry for "savings" a long "ā" vowel

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg outline for "explicit" to the Plover `EBGS/PHREUFT` outline since `SKHREUFT` is a private Di dictionary entry.
=> Change Gutenberg outline for "explicit" to Plover `EBGS/PHREUFT` outline

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg dictionary outline for "laurel" to `HRAU/REL`, as `HRAURL` outputs the capitalised name "Laurel".
=> Change Gutenberg dictionary outline for "laurel" to `HRAU/REL` as

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover `TRERPL` outline for "tremor" to `dict.json`, and have the Gutenberg dictionary prefer it.
=> Add Plover `TRERPL` outline for "tremor".

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the vowel sound in Gutenberg outline for "believer" to be a long "ē" to more accurately match word pronunciation.
=> Change vowel sound in Gutenberg outline for "believer" to be a long "ē".

dictionaries/dict-en-AU-with-extra-stroke.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add some new AU outlines and have the Gutenberg dictionary prefer them:
- `TKEUS/HO*RPB/A*U` for "dishonoured" based on Plover `TKEUS/HO*RPB` outline for "dishonor"
- `HR-FL/A*U` for "wilful" based on Plover `HR-FL` outline for "willful"
=> Add some new AU outlines for "wilful" and "dishonour"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the single-stroke Plover `KA*FLS` outline for "calves" to `dict.json`, and have the Gutenberg dictionary prefer it.
=> Add single-stroke Plover `KA*FLS` outline for "calves"

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the outline for "weaving" used in the Gutenberg dictionary to have a long "ē" vowel (`WAOEFG`) to more accurately reflect word pronunciation.
=> Change outline for "weaving" used in the Gutenberg dictionary to have a long "ē" vowel.

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-100-words.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json, dictionaries/top-200-words-spoken-on-tv.json
This PR proposes to add the following Plover outlines to the dictionaries:
- `SP` for "and"
- `SED` for "said"
The ripple effects of this extend to all of the "top-x" dictionaries, so this PR also proposes to update them all to use these outlines.
=> Add Plover outlines for "and" and "said"

dictionaries/top-10000-project-gutenberg-words.json
Following on from the discussion in #465, this PR proposes to fix entry for the `PO` outline ,as it outputs lowercase "po" and not capitalised "Po" (and because "po" lowercased is likely the entry that was intended for the Gutenberg dictionary).
Fixes #465.
=> Fix entry for `PO` outline as it outputs lowercase "po" and not capitalised "Po".

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-100-words.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json, dictionaries/top-200-words-spoken-on-tv.json
This PR proposes to add the Plover outline `AS` for "as" to `dict.json`, and prefer it in all the other top-x dictionaries over `AZ` due to not having to reach for the `Z` key.
=> Add Plover outline `AS` for "as"

dictionaries/dict.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover `TP*EL` outline for "fellow" and have the top-x dictionaries prefer it.
=> Add Plover `TP*EL` outline for "fellow"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to remove the condensed stroke for "civilisation" as it outputs "civil isation".
As a result of this, have the Gutenberg dictionary prefer the AU dictionary outline `SEUFLGS/A*U`.
=> Remove condensed stroke for "civilisation" as it outputs "civil isation"

dictionaries/dict-en-AU-with-extra-stroke.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a new "lustre" AU stroke based on current Plover single-stroke `HRUFRT` outline for "luster", and have the Gutenberg dictionary prefer it.
=> Add "lustre" AU stroke based on current Plover `HRUFRT` outline for "luster"

dictionaries/condensed-strokes.json, dictionaries/dict-en-AU-with-extra-stroke.json, dictionaries/top-1000-words.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a `HO*RPB/A*U` AU stroke for "honour" based on the Plover `HO*RPB` outline for "honor", and have the other dictionaries prefer it. As a result of this, also remove fingerspelling condensed stroke for "honour" as it would not be used anymore.
=> Add `HO*RPB/A*U` AU stroke for "honour" based on Plover `HO*RPB` outline.

dictionaries/condensed-strokes.json
`THE/S-R` outputs "they Sr.", so this PR proposes to change the "they have" outline to the correct `THE/SR`.
=> Fix "they have" outline typo

dictionaries/bad-habits.json, dictionaries/dict.json
Plover says `AES/ES` is another outline for "{^'s}", and not "'s", so this PR proposes to mark the latter as a mis-stroke and fix the entry in `dict.json`.
=> Change `AES/ES` from "'s" to "{^'s}"

dictionaries/condensed-strokes.json
This PR proposes to add a `"HOR/TKEFRBZ": "hors d'oeuvres"` condensed stroke to the word's already ample collection of outlines.
=> Add `HOR/TKEFRBZ` condensed stroke for "hors d'oeuvres"

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a `TPHAEPLS` condensed stroke for "enemies" based on the `TPHAEPL` Plover outline for "enemy", and have the Gutenberg dictionary prefer it.
=> Add `TPHAEPLS` condensed stroke for "enemies"

dictionaries/condensed-strokes.json
This PR proposes to add an `ARBGTS` condensed stroke for "actors". `dict.json` and Plover already have an existing `A*RBGTS` entry for "actors", but it seems that the un-asterisked version works as well.
=> Add `ARBGTS` condensed stroke for "actors".

dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to change the Gutenberg entry for "eagle" from `AOEG/*L` to `AOEG/-L`, simply because it's one less key to press.
=> Change Gutenberg entry for "eagle" from `AOEG/*L` to `AOEG/-L`.

dictionaries/bad-habits.json, dictionaries/dict.json
This PR proposes to mark `WAFR` outline for "wafer" as a mis-stroke as it outputs "waver", and change the existing `WAFR` dictionary entry to the correct "waver".
=> Mark `WAFR` for "wafer" as a mis-stroke as it outputs "waver".

dictionaries/condensed-strokes.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add a single-stroke `SRERPBTD` condensed stroke for "ventured", and have the Gutenberg dictionary prefer it.
=> Add `SRERPBTD` condensed stroke for "ventured" and have the Gutenberg

dictionaries/dict.json
This PR proposes to fix what looks like a typo in the outline for "arteries", which would seem to prevent it from being shown in Typey Type. I definitely think that `RARTS` is an easier stroke than `RARTSZ`, which is very difficult to stroke without also accidentally hitting the `D` key.
=> Remove initial space from "arteries" outline.

dictionaries/condensed-strokes.json
The Typey Type exercises have the outline for "hens" listed as `HEPB/-S`, so this PR proposes to add a single-stroke condensed stroke for "hens".
=> Add single-stroke `HEPBZ` condensed stroke for "hens".

dictionaries/bad-habits.json, dictionaries/dict.json
This PR proposes to mark the `STPHU` outline for "you?" as a mis-stroke as it does not seem to exist in Plover's dictionary.
=> Mark `STPHU` outline for "you?" as a mis-stroke.

dictionaries/bad-habits.json, dictionaries/dict.json
This PR proposes to mark `K*EF` for "contraceptive" as a mis-stroke, as Plover now officially outputs "Kev".
=> Mark `K*EF` for "contraceptive" as a mis-stroke, as Plover now outputs "Kev".

dictionaries/bad-habits.json, dictionaries/dict.json
This PR proposes to mark `TKUPB` for "{&dun-}" as a mis-stroke since Plover now specifies `TKUPB` to be simply "dun".
=> Mark `TKUPB` for `"{&dun-}"` as a mis-stroke

dictionaries/condensed-strokes.json
This PR proposes to add a `REUPBG/*ER` condensed stroke for "ringer".
=> Add `REUPBG/*ER` condensed stroke for "ringer"

dictionaries/condensed-strokes.json
Condensed stroke `STOR/KWREU` for "storey" is already a named Plover outline in `dict.json` for "story".
So, this PR proposes to change the condensed stroke entry to `STOR/TK-LS/KWREU` (I couldn't figure out anything better...).
=> Replace condensed stroke `STOR/KWREU` for "storey"

dictionaries/dict.json
This PR proposes to add the Plover outline `KPEUPBS` for "existence" to `dict.json`.
I was also considering proposing to change the top-x dictionaries preference for "existence" from the current `KPEUFS` to `KPEUPBS`: even though it's longer, I find it much easier to stroke. But, since `KPEUFS` is a fine outline, I don't think I could objectively suggest the change.
=> Add Plover outline `KPEUPBS` for "existence" to `dict.json`

dictionaries/condensed-strokes.json
This PR proposes to add a condensed stroke `HOUSZ` for "houses".
=> Add condensed stroke `HOUSZ` for "houses"

dictionaries/dict.json
This PR simply proposes to add the Plover `RE/TRAOEFR` outline for "retriever" to `dict.json`.
=> Add Plover `RE/TRAOEFR` outline for "retriever"

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json
The `O*EU` outline outputs "oi" in Plover, so this PR proposes to make the following changes:
- Change `dict.json` entry for `O*EU` to "oi"
- Add bad habits entry for `O*EU` as "oy"
- Add a named fingerspelled condensed stroke entry for "oy"
=> Make `O*EU` outline-related changes

dictionaries/condensed-strokes.json
This PR proposes to add some condensed strokes that have come up while I was doing the [Apostrophes Typey Type exercise](https://didoesdigital.com/typey-type/lessons/drills/apostrophes/) that reduce the outline in some way, either by characters or strokes, from what is in the Plover dictionary.
=> Add condensed stroke from Apostrophes lesson

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json
There is no longer a named Plover outline for "gentlemen's". Therefore, this PR proposes to:
- move the original entry from `dict.json` to `bad-habits.json` (it would need to go there anyway since `SKWRE/AES` now outputs "e's"
- create a condensed stroke for "gentlemen's", using the shortest official outline for "gentlemen"
=> Fix outline for "gentlemen's"

dictionaries/bad-habits.json, dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
Outline `OERPBT` outputs "interior", rather than "ordinary, reasonable, and prudent", therefore this PR proposes the following changes based on what issues I found while doing Typey Type's [Steno party tricks lesson](https://didoesdigital.com/typey-type/lessons/drills/steno-party-tricks/):
- Mark `OERPBT` for "ordinary, reasonable, and prudent" as a mis-stroke
- Fix `OERPBT` entry in `dict.json` to have value "interior"
- Have the Gutenberg dictionary prefer the single stroke `OERPBT` outline for "interior"
=> Fix outline value for `OERPBT`

dictionaries/bad-habits.json, dictionaries/dict.json
This is an issue found in Typey Type's [Two-word briefs How * lesson](https://didoesdigital.com/typey-type/lessons/collections/two-word-briefs-same-beginnings/how/).
Outline `HOULD` outputs "how would", rather than "how old", therefore, this PR proposes to:
- Mark `HOULD` for "how old" as a mis-stroke
- Fix `HOULD` entry in `dict.json` to have value "how would"
=> "Two-word briefs How *" lesson fix

dictionaries/bad-habits.json, dictionaries/dict.json
While doing the ["Two-word briefs Where *" lesson](https://didoesdigital.com/typey-type/lessons/collections/two-word-briefs-same-beginnings/where/) on Typey Type, I found an entry that looks like it's been updated in Plover, so this PR proposes to add that update to the dictionaries.
=> "Two-word briefs Where *" fix

dictionaries/bad-habits.json, dictionaries/dict.json
While doing the ["Two-word briefs Of *" lesson](https://didoesdigital.com/typey-type/lessons/collections/two-word-briefs-same-beginnings/of/) on Typey Type, I found an entry that looks like it's been updated in Plover, so this PR proposes to add that update to the dictionaries.
=> "Two-word briefs Of *" fix

dictionaries/bad-habits.json, dictionaries/dict.json
While doing the ["Two-word briefs * in" lesson](https://didoesdigital.com/typey-type/lessons/collections/two-word-briefs-same-endings/in/) on Typey Type, I found some entries that look like they've been updated in Plover, so this PR proposes to add those updates to the dictionaries.
=> "Two word briefs * in" fixes

dictionaries/bad-habits.json, dictionaries/dict.json
While doing the ["Two-word briefs * of" lesson](https://didoesdigital.com/typey-type/lessons/collections/two-word-briefs-same-endings/of/) on Typey Type, I found some entries that look like they've been updated in Plover, so this PR proposes to add those updates to the dictionaries.
=> "Two word briefs * of" fixes

dictionaries/condensed-strokes.json
This PR proposes to add a condensed stroke for "assets and liabilities", `SA*ETS/SKP/HRAOEUBLTS`, that uses the `SA*ETS` single-stroke outline for "assets".
=> Add condensed stroke for "assets and liabilities"

dictionaries/condensed-strokes.json, dictionaries/dict.json
Outline `PHEUBG/*L` has a Plover entry to output the name "Mikel", therefore, this PR proposes to:
- Add `PHEUBG/*L` for "Mikel" to `dict.json`
- Change condensed stroke for "mickle" from `PHEUBG/*L` to
`PHEUBG/TK-LS/HR*/*E`
=> Add `PHEUBG/*L` outline for "Mikel"

dictionaries/bad-habits.json, dictionaries/condensed-strokes.json, dictionaries/dict.json
The outline `TW*EUBGS` outputs "twixt", rather than "'twixt". Therefore, this PR proposes to:
- Mark `TW*EUBGS` for "'twixt" as a mis-stroke
- Change `dict.json` entry for `TW*EUBGS` to have value "twixt"
- Add `A*E/TW*EUBGS` condensed stroke for "'twixt"
=> Change "twixt"-related outlines.

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add some Plover outlines for "chicken", "trouser", and "magnetic" into the main dictionary, and have the Gutenberg dictionary prefer the single-stroke outlines for "chicken" and "magnetic".
=> Add plover outlines

dictionaries/condensed-strokes.json, dictionaries/dict-en-AU-with-extra-stroke.json
This PR proposes to add a one-stroke `TRAFRLS` condensed stroke outline for "travelers" and an AU stroke based on it.
=> Add one-stroke `TRAFRLS` condensed stroke outline for "travelers"

dictionaries/dict.json, dictionaries/top-10000-project-gutenberg-words.json
This PR proposes to add the Plover outline `TKAEPL` for "damn" and have the Gutenberg dictionary prefer it.
=> Add Plover outline `TKAEPL` for "damn"

dictionaries/dict.json
This PR proposes to add the `HR*UFRPB` Plover outline for "lunch" to `dict.json`.
=> Add `HR*UFRPB` Plover outline for "lunch".

dictionaries/bad-habits.json, dictionaries/dict.json
Although it is a valid Plover outline, this PR proposes to mark `PHA/POEL/KWROPB` for "Napoleon" as a mis-stroke, since it pronounces as "Mapoleon", and all the other outlines for "Napoleon" contain the correct first stroke `TPHA`.
=> Mark `PHA/POEL/KWROPB` for "Napoleon" as a mis-stroke.

README.md
This PR proposes to make a couple of changes to the Tabbing section of the README:
- Re-format the paragraph that describes tabbing into a bulleted list for a bit more ease of readability
- Fix typo regarding `TW-G` being used in place of `TW-P`
- Add `<kbd>` tags to more prominently distinguish the commands as key presses
The final point was deliberately done as a separate commit since not everyone seems to like `<kbd>` tags, so I'd be happy to remove them if they look out of place in the README.
=> Fix Tabbing section of README

README.md
It should be `P*ERS` with the asterisk (according to [punctuation.json](https://github.com/didoesdigital/steno-dictionaries/blob/master/dictionaries/punctuation.json))
=> Fix percentage sign stroke symbol in README
